action = [
            [["pass", "passu"], ["passing", "passu"], ["passed", "passu shita"], ["passes", "passu suru"], ["", ""]],
            [["change", "kaeru"], ["changing", "kaete iru"], ["changed", "kaetta"], ["changes", "kaeru"], ["", ""]],
            [["visit", "hōmon suru"], ["visits", "hōmon suru"], ["visiting", "hōmon shite iru"], ["visited", "hōmon shita"], ["", ""]],
            [["leave", "saru"], ["leaving", "satte iru"], ["leaves", "saru"], ["", ""], ["", ""]],
            [["player", "pureiyaa"], ["playing", "asobu"], ["played", "asonda"], ["plays", "asobu"]],
            [["pull", "hiku"], ["pulling", "hiku"], ["pulled", "hita"], ["pulls", "hiku"], ["", ""]],
            [["hope", "kitai"], ["hopeful", "kitai suru"], ["hoping", "kitai suru"], ["hoped", "kitai shita"], ["hopes", "kitai suru"]],
            [["do", "suru"], ["doing", "suru"], ["done", "shita"], ["does", "suru"], ["", ""]],
            [["reach", "tōtaru"], ["reaching", "tōtaru"], ["reached", "tōtta"], ["reaches", "tōtaru"], ["", ""]],
            [["go", "iku"], ["going", "iku"], ["gone", "itta"], ["", ""], ["", ""]],
            [["can", "dekiru"], ["can not", "dekimasen"], ["", ""], ["", ""], ["", ""]],
            [["fold", "oru"], ["folds", "oru"], ["folding", "ori"], ["folded", "orita"], ["", ""]],
            [["like", "suki"], ["likes", "suki"], ["liking", "suki"], ["liked", "sukida"], ["", ""]],
            [["pour", "sasu"], ["pouring", "sasu"], ["poured", "sashita"], ["", ""], ["", ""]],
            [["squeeze", "shiboru"], ["squeezes", "shiboru"], ["squeezing", "shibotte iru"], ["squeezed", "shiborita"], ["", ""]],
            [["hit", "ataru"], ["hits", "ataru"], ["hitting", "atte iru"], ["hit", "atta"], ["", ""]],
            [["blow", "fuku"], ["blows", "fuku"], ["blowing", "fuite iru"], ["blew", "fuita"], ["", ""]],
            [["paintbrush", "fude"], ["paintbrushing", "fude o tsukau"], ["paintbrushed", "fude o tsukatta"], ["", ""]],
            [["speak", "hanasu"], ["speaking", "hanasu"], ["spoke", "hanashita"], ["speaker", "hanashite iru"], ["", ""]],
            [["resume", "saishū"], ["resuming", "saishū suru"], ["resumed", "saishū shita"], ["", ""]],
            [["progress", "shinpo"], ["progresses", "shinpo suru"], ["progressing", "shinpo shite iru"], ["progressed", "shinpo shita"], ["", ""]],
            [["connection", "kankei"], ["connect", "tsunagu"], ["connects", "tsunagu"], ["connecting", "tsunagatte iru"], ["connected", "tsunagatta"], ["", ""]],
            [["cause", "yōin"], ["causes", "yōin suru"], ["causing", "yōin shite iru"], ["caused", "yōin shita"], ["", ""]],
            [["enjoy", "tanoshimu"], ["enjoyment", "tanoshimu"], ["enjoys", "tanoshimu"], ["enjoying", "tanoshinde iru"], ["enjoyed", "tanoshinda"]],
            [["catch", "tsukamu"], ["catches", "tsukamu"], ["catching", "tsukande iru"], ["caught", "tsukanda"], ["", ""]],
            [["protect", "mamoru"], ["protects", "mamoru"], ["protecting", "mamotte iru"], ["protected", "mamotta"], ["", ""]],
            [["look", "miru"], ["looks", "miru"], ["looking", "mite iru"], ["looked", "mita"], ["", ""]],
            [["work", "shigoto"], ["works", "shigoto suru"], ["working", "shigoto shite iru"], ["worked", "shigoto shita"], ["", ""]],
            [["put", "oku"], ["puts", "oku"], ["putting", "okite iru"], ["put", "okita"], ["", ""]],
            [["ride", "norimasu"], ["rides", "norimasu"], ["riding", "nobite iru"], ["rided", "nori"], ["", ""]],
            [["come", "kuru"], ["comes", "kimasu"], ["coming", "kuru"], ["came", "kita"], ["", ""]],
            [["take", "toru"], ["takes", "torimasu"], ["taking", "torite iru"], ["took", "took"], ["taken", "torareta"], ["", ""]],
            [["dry", "kawaita"], ["dries", "kawaitemasu"], ["drying", "kawaitemasu"], ["", ""]],
            [["apply", "tekikaku suru"], ["applies", "tekikaku shimasu"], ["applying", "tekikaku shite iru"], ["applied", "tekikaku shita"], ["", ""]],
            [["jump", "tobu"], ["jumps", "tobu"], ["jumping", "tobite iru"], ["jumped", "tobita"], ["", ""]],
            [["crowd", "kōran"], ["crowds", "kōran"], ["crowded", "kōran shita"], ["", ""], ["", ""]],
            [["answer", "kotaeru"], ["answers", "kotaeru"], ["answering", "kotaete iru"], ["answered", "kotaeta"], ["", ""]],
            [["teacher", "sensei"], ["teach", "oshieru"], ["teaches", "oshieru"], ["teaching", "oshieru"], ["taught", "oshieta"]],
            [["receive", "ukeru"], ["receives", "ukeru"], ["receiving", "ukete iru"], ["received", "uketa"], ["", ""]],
            [["hear", "kiku"], ["hears", "kiku"], ["hearing", "kikite iru"], ["heard", "kikimashita"], ["", ""]],
            [["listen", "kiku"], ["listens", "kiku"], ["listening", "kikite iru"], ["listened", "kikimashita"], ["", ""]],
            [["believer", "shinjite iru hito"], ["believe", "shinjiru"], ["believes", "shinjiru"], ["believing", "shinjite iru"], ["believed", "shinjita"]],
            [["request", "yōkyū"], ["requests", "yōkyū suru"], ["requesting", "yōkyū shite iru"], ["requested", "yōkyū shita"], ["", ""]],
            [["search", "kensaku"], ["searches", "kensaku suru"], ["searched", "kensaku shita"], ["searching", "kensaku shite iru"], ["", ""]],
            [["pick", "tori"], ["pick up", "tori ageru"], ["picks up", "tori ageru"], ["picked up", "tori agemashita"], ["", ""]],
            [["convert", "tenkai"], ["converts", "tenkai suru"], ["converting", "tenkai shite iru"], ["converted", "tenkai shita"], ["", ""]],
            [["take", "toru"], ["takes", "toru"], ["taking", "totte iru"], ["took", "totta"], ["", ""]],
            [["dig", "horu"], ["digs", "horu"], ["digging", "horu"], ["dug", "hottā"], ["", ""]],
            [["push", "osu"], ["pushes", "osu"], ["pushed", "oshita"], ["pushing", "oshite iru"], ["", ""]],
            [["put", "oku"], ["puts", "oku"], ["putting", "okite iru"], ["put", "okita"], ["", ""]],
            [["climb", "noboru"], ["climbs", "noboru"], ["climbing", "nobotte iru"], ["climbed", "nobotta"], ["", ""]],
            [["use", "tsukau"], ["uses", "tsukau"], ["using", "tsukatte iru"], ["used", "tsukatta"], ["", ""]],
            [["raise", "ageru"], ["raises", "ageru"], ["raising", "ageru"], ["raised", "age"], ["", ""]],
            [["fly", "tobu"], ["flies", "tobu"], ["flying", "tobite iru"], ["flied", "tobita"], ["", ""]],
            [["work", "shigoto suru"], ["works", "shigoto suru"], ["working", "shigoto shite iru"], ["worked", "shigoto shita"], ["", ""]],
            [["get up", "okiru"], ["", ""], ["", ""], ["", ""], ["", ""]],
            [["carry", "hakobu"], ["carries", "hakobu"], ["carrying", "hakobite iru"], ["carried", "hakonda"], ["", ""]],
            [["play", "asobu"], ["playing", "asonde iru"], ["played", "asonda"], ["", ""], ["", ""]],
            [["read", "yomu"], ["reads", "yomu"], ["reading", "yonde iru"], ["", ""], ["", ""]],
            [["come", "kuru"], ["comes", "kuru"], ["coming", "kuru"], ["came", "kita"], ["", ""]],
            [["sit", "suwaru"], ["sits", "suwaru"], ["sitting", "suwatte iru"], ["sat", "suwatta"], ["", ""]],
            [["clear", "kirei ni suru"], ["cleared", "kirei ni shita"], ["clearing", "kirei ni shite iru"], ["cleared", "kirei ni shita"], ["", ""]],
            [["wake up", "okiru"], ["wakes up", "okiru"], ["woke up", "okita"], ["", ""], ["", ""]],
            [["turned", "mawari"], ["turns", "mawaru"], ["turned", "mawari"], ["turning", "mawari"], ["", ""]],
            [["draw", "kaku"], ["draws", "kaku"], ["drawing", "kaku"], ["drew", "kaita"], ["", ""]],
            [["write", "kaku"], ["writes", "kaku"], ["writing", "kaku"], ["wrote", "kaita"], ["", ""]],
            [["arrive", "tōchaku suru"], ["arrives", "tōchaku suru"], ["arriving", "tōchaku shite iru"], ["arrived", "tōchaku shita"], ["", ""]],
            [["eat", "taberu"], ["eating", "tabete iru"], ["ate", "tabeta"], ["eats", "taberu"], ["", ""]],
            [["open", "aku"], ["opening", "aku"], ["opener", "akemono"], ["opened", "akemashita"], ["open", "aku"]],
            [["order", "chūmon"], ["ordering", "chūmon suru"], ["ordered", "chūmon shita"], ["orders", "chūmon suru"], ["", ""]],
            [["confirm", "kakunin suru"], ["confirming", "kakunin shite iru"], ["confirmed", "kakunin shita"], ["confirms", "kakunin suru"], ["", ""]],
            [["break", "kowasu"], ["breaking", "kowasu"], ["broke", "kowashita"], ["breaks", "kowasu"], ["", ""]],
            [["smoke", "kemuri"], ["smoking", "kemuri o suru"], ["smoked", "kemuri o shita"], ["smokes", "kemuri"]],
            [["wash", "arau"], ["washing", "aratte iru"], ["washed", "aratta"], ["washes", "arau"], ["", ""]],
            [["speak", "hanasu"], ["speaking", "hanashite iru"], ["spoke", "hanashita"], ["spoken", "hanashita"], ["speaks", "hanasu"]],
            [["find", "mitsukeru"], ["finding", "mitsukete iru"], ["founded", "mitsuketa"], ["", ""], ["", ""]],
            [["give", "ageru"], ["giving", "ageru"], ["given", "ataeru"], ["gave", "ageru"], ["gives", "ageru"]],
            [["fly", "tobu"], ["flying", "tobite iru"], ["flew", "tobita"], ["flies", "tobu"], ["", ""]],
            [["catch", "tsukamu"], ["catching", "tsukamu"], ["catched", "tsukatta"], ["catches", "tsukamu"], ["", ""]],
            [["twist", "nejiru"], ["twisting", "nejite iru"], ["twisted", "nejita"], ["twists", "nejiru"], ["", ""]],
            [["enter", "hairu"], ["entering", "hairu"], ["entered", "haita"], ["entres", "hairu"], ["", ""]],
            [["miss", "misu"], ["missing", "misu"], ["missed", "misshita"], ["misses", "misu"], ["", ""]],
            [["see", "miru"], ["seeing", "miru"], ["saw", "mita"], ["sees", "miru"], ["", ""]],
            [["taste", "ajiwau"], ["tasting", "ajiwau"], ["tasted", "ajiwaita"], ["tastes", "ajiwau"], ["", ""]],
            [["revise", "kōsokusu"], ["revision", "kōsokusu"], ["revised", "kōsokushita"], ["", ""]],
            [["runner", "rannā"], ["running", "hashiru"], ["ran", "hashitta"], ["runs", "hashiru"], ["", ""]],
            [["study", "benkyō suru"], ["studying", "benkyō shite iru"], ["studied", "benkyō shita"], ["studies", "benkyō suru"], ["", ""]],
            [["talk", "hanasu"], ["talking", "hanashite iru"], ["talked", "hanashita"], ["talks", "hanasu"], ["", ""]],
            [["lose", "ushinau"], ["losing", "ushinau"], ["lost", "ushinatta"], ["loses", "ushinau"], ["", ""]],
            [["move", "ugoku"], ["movement", "ugoki"], ["moving", "ugokite iru"], ["moved", "ugokashita"], ["moves", "ugoku"]],
            [["swim", "oyogu"], ["swimming", "oyogi"], ["swam", "oyoita"], ["swims", "oyogu"], ["", ""]],
            [["turn", "mawasu"], ["turning", "mawasu"], ["turned", "mawashita"], ["turns", "mawasu"], ["", ""]],
            [["become", "naru"], ["becoming", "natte iru"], ["became", "natta"], ["becomes", "naru"], ["", ""]],
            [["soil", "tsuchi"], ["soiling", "tsuchi"], ["soiled", "tsuchi"], ["", ""]],
            [["place", "oki"], ["placing", "oki"], ["placed", "oki"], ["", ""]],
            [["pollute", "kōsai"], ["polluted", "kōsai shita"], ["pollution", "kōsai"], ["", ""]],
            [["rain", "ame"], ["raining", "ame ga furu"], ["rained", "ame ga furu"], ["", ""]],
            [["vacate", "kūshi"], ["vacated", "kūshi shita"], ["vacation", "kūshi"], ["", ""]],
            [["rent", "yachin"], ["renting", "yachin suru"], ["rented", "yachin shita"], ["", ""]],
            [["flood", "sai"], ["floods", "sai"], ["flooded", "sai shita"], ["", ""]],
            [["fold", "oru"], ["folds", "oru"], ["folding", "oru"], ["folded", "orimashita"], ["", ""]],
            [["corner", "kado"], ["corners", "kado"], ["cornering", "kado"], ["cornered", "kado"], ["", ""]],
            [["bill", "seikyūsho"], ["billing", "seikyū"], ["bills", "seikyū"], ["", ""]],
            [["cost", "kosuto"], ["costs", "kosuto"], ["costing", "kosuto suru"], ["costed", "kosuto shita"], ["", ""]],
            [["smoke", "kemuri"], ["smokes", "kemuri"], ["smoking", "kemuri o suru"], ["smoked", "kemuri o shita"], ["", ""]],
            [["close", "sō"], ["closes", "sō"], ["closing", "sō"], ["closely", "chikai"], ["closed", "sōshita"]],
            [["bright", "akarui"], ["brightening", "akarui"], ["brightly", "akarui"], ["brightened", "akarui"], ["", ""]],
            [["calculator", "keisanki"], ["calculated", "keisan shita"], ["calculating", "keisan shite iru"], ["", ""]],
            [["cash", "genkin"], ["cashed", "genkin shita"], ["cashing", "genkin shite iru"], ["cashes", "genkin suru"]],
            [["toy", "asobi"], ["toyed", "asobimashita"], ["toying", "asobite iru"], ["toys", "asobu"]],
            [["stare", "jirojiro miru"], ["staring", "jirojiro mite iru"], ["stared", "jirojiro mita"], ["stares", "jirojiro miru"]],
            [["rub", "nuru"], ["rubbing", "nuru"], ["rubbed", "nuru"], ["rubs", "nuru"]],
            [["seat", "seki"], ["seating", "seki ni suwaru"], ["seats", "seki"], ["", ""]],
            [["drink", "nomu"], ["dranked", "nonda"], ["drank", "nonda"], ["drinking", "nonde iru"], ["drinks", "nomu"]],
            [["microwave", "wātāsuto"], ["microwaved", "wātāsuto shita"], ["microwaving", "wātāsuto shite iru"], ["microwaves", "wātāsuto suru"]],
            [["refrigerator", "reijō"], ["refrigeration", "reijō"], ["refrigerating", "reijō shite iru"], ["refrigerated", "reijō shita"], ["refrigerates", "reijō suru"]],
            [["bandage", "bandēji"], ["bandaged", "bandēji o shita"], ["bandages", "bandēji"]],
            [["computer", "konpyūta"], ["computing", "konpyūta suru"], ["computed", "konpyūta shita"], ["computes", "konpyūta suru"]],
            [["air conditioner", "eakon"], ["air conditioned", "eakon shita"], ["air conditions", "eakon o suru"], ["", ""]],
            [["tape", "tēpu"], ["taping", "tēpu o suru"], ["taped", "tēpu shita"], ["tapes", "tēpu o suru"]],
            [["shave", "soru"], ["shaving", "soru"], ["shaved", "sotta"], ["shaves", "soru"]],
            [["toothbrush", "haburashi"], ["toothbrushing", "haburashi o suru"], ["toothbrushes", "haburashi"], ["", ""]],
            [["conditioner", "kondishonā"], ["conditioning", "kondishonā suru"], ["conditioned", "kondishonā shita"], ["conditions", "kondishonā suru"]],
            [["whiteboard", "howaito bōdo"], ["whiteboarding", "howaito bōdo o tsukau"], ["", ""], ["", ""]],
            [["book", "hon"], ["books", "hon"], ["booking", "yoyaku suru"], ["booked", "yoyaku shita"]],
            [["eraser", "keshigomu"], ["erasing", "keshigomu o suru"], ["erased", "keshigomu o shita"], ["erases", "keshigomu o suru"]],
            [["mailbox", "yūbin posuto"], ["mailboxing", "yūbin posuto o tsukau"], ["mailboxed", "yūbin posuto ni oite"], ["mailboxes", "yūbin posuto"]],
            [["information", "jōhō"], ["informing", "jōhō o tsutaeru"], ["informed", "jōhō o tsutaeta"], ["informer", "tsutaeru hito"], ["informs", "jōhō o tsutaeru"]],
            [["scissor", "hasami"], ["scissoring", "hasami o suru"], ["scissors", "hasami"], ["", ""]],
            [["ruler", "jōgi"], ["ruling", "jōgi o suru"], ["ruled", "jōgi o shita"], ["rules", "jōgi"]],
            [["glue", "nori"], ["glueing", "nori o tsukau"], ["glued", "nori o tsukemashita"], ["glues", "nori o tsukau"]],
            [["ring", "yubiwa"], ["ringing", "yubiwa o suru"], ["ranged", "yubiwa o shita"], ["ringed", "yubiwa"], ["rings", "yubiwa"]],
            [["remote control", "rimokon"], ["remote controlling", "rimokon o suru"], ["remote controlled", "rimokon o shita"], ["remote controls", "rimokon"]],
            [["duck", "kagamu"], ["ducking", "kagamu"], ["ducked", "kagatta"], ["ducks", "kagamu"], ["", ""]],
            [["mirror", "kagami"], ["mirroring", "kagami o utsusu"], ["mirrored", "kagami o utsushita"], ["mirrors", "kagami o utsusu"], ["", ""]],
            [["printer", "purintā"], ["printing", "purinto suru"], ["printed", "purinto shita"], ["prints", "purinto suru"], ["", ""]],
            [["teacher", "sensei"], ["teaching", "oshieru"], ["teached", "oshieta"], ["teaches", "oshieru"], ["", ""]],
            [["gardener", "niwashi"], ["gardening", "niwa o sodateru"], ["gardened", "niwa o sodate"], ["gardens", "niwa o sodateru"], ["", ""]],
            [["programmer", "puroguramaa"], ["programming", "puroguramingu"], ["programmed", "puroguramu shita"], ["programmes", "puroguramu"], ["", ""]],
            [["migrant", "imin"], ["migrating", "imin suru"], ["migrated", "imin shita"], ["migrates", "imin suru"], ["", ""]],
            [["occupation", "shokugyo"], ["occupying", "shoyū suru"], ["occupied", "shoyū shita"], ["occupies", "shoyū suru"], ["", ""]],
            [["singer", "kashu"], ["sing", "utau"], ["singing", "utatte iru"], ["sang", "utatta"], ["sings", "utau"]],
            [["accountant", "kaikeishi"], ["accounting", "kaikei suru"], ["accounted", "kaikei shita"], ["accounts", "kaikei suru"], ["", ""]],
            [["farm", "nojo"], ["farmer", "nōtei"], ["farmed", "nōtei shita"], ["farms", "nōtei"], ["", ""]],
            [["management", "keiei"], ["manager", "manejaa"], ["managing", "keiei suru"], ["managed", "keiei shita"], ["manages", "keiei suru"]],
            [["driver", "doraibā"], ["drive", "undou suru"], ["driving", "undō shite iru"], ["drived", "undō shita"], ["drives", "undou suru"]],
            [["group", "gurūpu"], ["grouping", "gurūpu suru"], ["grouped", "gurūpu shita"], ["groups", "gurūpu"], ["", ""]],
            [["throw", "nageru"], ["throwing", "nageru"], ["threw", "nageta"], ["throws", "nageru"], ["", ""]],
            [["withdraw", "suru"], ["withdrawing", "suru"], ["withdrawn", "suru"], ["withdrew", "suru"], ["", ""]],
            [["finish", "owaru"], ["finishing", "owatte iru"], ["finished", "owatta"], ["finishes", "owaru"], ["", ""]],
            [["relax", "rirakkusu suru"], ["relaxing", "rirakkusu suru"], ["relaxed", "rirakkusu shita"], ["relaxes", "rirakkusu suru"], ["", ""]],
            [["cook", "ryōri suru"], ["cooking", "ryōri suru"], ["cooked", "ryōri shita"], ["cooks", "ryōri suru"], ["", ""]],
            [["exercise", "undō suru"], ["exercising", "undō suru"], ["exercised", "undō shita"], ["exercises", "undō suru"], ["", ""]],
            [["die", "shinu"], ["dying", "shinde iru"], ["died", "shinda"], ["dies", "shinu"], ["", ""]],
            [["attend", "sanka suru"], ["attending", "sanka suru"], ["attends", "sanka suru"], ["", ""]],
            [["say", "iu"], ["saying", "itte iru"], ["said", "itta"], ["says", "iu"], ["", ""]],
            [["call", "yobu"], ["caller", "yobimasu"], ["calling", "yobite iru"], ["called", "yobita"], ["calls", "yobu"]],
            [["cough", "seki o suru"], ["coughing", "seki o suru"], ["coughed", "seki o shita"], ["", ""]],
            [["reserve", "yoyaku suru"], ["reservation", "yoyaku"], ["reserving", "yoyaku suru"], ["reserved", "yoyaku shita"], ["reserves", "yoyaku suru"]],
            [["marry", "kekkon suru"], ["marrying", "kekkon suru"], ["married", "kekkon shita"], ["marries", "kekkon suru"], ["", ""]],
            [["participate", "sanka suru"], ["participation", "sanka"], ["participated", "sanka shita"], ["", ""]],
            [["engage", "sōsaku suru"], ["engaging", "sōsaku suru"], ["engaged", "sōsaku shita"], ["engages", "sōsaku suru"], ["", ""]],
            [["cheer", "ōen suru"], ["cheering", "ōen suru"], ["cheered", "ōen shita"], ["cheers", "ōen suru"], ["", ""]],
            [["park", "chūshō suru"], ["parking", "chūshō suru"], ["parked", "chūshō shita"], ["parks", "chūshō suru"], ["", ""]],
            [["export", "yushutsu suru"], ["exporting", "yushutsu suru"], ["exported", "yushutsu shita"], ["exports", "yushutsu suru"], ["", ""]],
            [["dizzy", "kakikomu"], ["", ""], ["", ""], ["", ""], ["", ""]],
            [["skip", "suru"], ["skipping", "suru"], ["skipped", "shita"], ["skips", "suru"], ["", ""]],
            [["burn", "yaku"], ["burning", "yakite iru"], ["burned", "yaketa"], ["burnt", "yaketa"], ["burns", "yaku"]],
            [["sale", "bai"], ["sell", "uru"], ["selling", "uru"], ["sold", "utta"], ["sells", "uru"]],
            [["mixture", "kōsō"], ["mix", "mazeru"], ["mixing", "mazete iru"], ["mixed", "mazeta"], ["mixes", "mazeru"]],
            [["help", "tasukeru"], ["helping", "tasukeru"], ["helped", "tasuketa"], ["helps", "tasukeru"], ["", ""]],
            [["start", "hajimeru"], ["starting", "hajimeru"], ["started", "hajimemashita"], ["starts", "hajimeru"], ["", ""]],
            [["welcome", "yōkoso"], ["welcoming", "yōkoso suru"], ["welcomed", "yōkoso shita"], ["welcomes", "yōkoso suru"], ["", ""]],
            [["import", "yunyū suru"], ["importing", "yunyū suru"], ["imported", "yunyū shita"], ["imports", "yunyū suru"], ["", ""]],
            [["hiccup", "shōsok"], ["hiccups", "shōsok"], ["", ""], ["", ""], ["", ""]],
            [["serve", "sāburu"], ["serving", "sāburu"], ["served", "sābureta"], ["serves", "sāburu"], ["", ""]],
            [["cut", "kiru"], ["cutting", "kiru"], ["cut", "kitta"], ["cuts", "kiru"], ["", ""]],
            [["frustration", "furasutō"], ["frustrated", "furasutēto"], ["frustrations", "furasutō"], ["", ""], ["", ""]],
            [["ask", "tazuneru"], ["asking", "tazuneru"], ["asked", "tazunemashita"], ["asks", "tazuneru"], ["", ""]],
            [["injury", "gai"], ["injure", "gai o suru"], ["injuring", "gai o suru"], ["injures", "gai o suru"], ["", ""]],
            [["fight", "tatakau"], ["fighting", "tatakau"], ["fought", "tatakatta"], ["fights", "tatakau"], ["", ""]],
            [["upset", "okoru"], ["upsetting", "okoru"], ["", ""], ["", ""], ["", ""]],
            [["worry", "shinpai"], ["worrying", "shinpai suru"], ["worried", "shinpai shite iru"], ["worries", "shinpai suru"], ["", ""]],
            [["driver", "doraibā"], ["drive", "doraibu"], ["driving", "doraibu"], ["drove", "doraibu shita"], ["drives", "doraibu suru"]],
            [["land", "riku"], ["landing", "riku ni kīru"], ["landed", "riku ni kīta"], ["lands", "riku ni kīru"], ["", ""]],
            [["confiscate", "yokin"], ["confiscating", "yokinsuru"], ["confiscation", "yokinsuru"], ["", ""], ["", ""]],
            [["declare", "sengen suru"], ["declaring", "sengen suru"], ["declared", "sengen shita"], ["declares", "sengen suru"], ["", ""]],
            [["commute", "通勤する (tsūkin suru)"], ["commuting", "tsūkin shite iru"], ["commuted", "tsūkin shita"], ["commutes", "tsūkin suru"], ["", ""]],
            [["sign", "サイン (sain)"], ["signing", "sain suru"], ["signed", "sain shita"], ["signs", "sain"], ["", ""]],
            [["respect", "sonkei"], ["respecting", "sonkei suru"], ["respected", "sonkei shita"], ["", ""], ["", ""]],
            [["thank", "arigatou"], ["thanks", "arigatou"], ["thanking", "arigatou suru"], ["thanked", "arigatou shita"], ["", ""]],
            [["love", "ai"], ["loving", "ai suru"], ["loved", "ai shita"], ["", ""], ["", ""]],
            [["sneeze", "kōsok"], ["sneezes", "kōsok"], ["sneezed", "kōsok shita"], ["sneezing", "kōsok shite iru"], ["", ""]],
            [["knock", "kuru"], ["knocks", "kuru"], ["knocking", "kuru"], ["knocked", "kutta"], ["", ""]],
            [["explanation", "setsumei"], ["explain", "setsumei suru"], ["explains", "setsumei suru"], ["explaining", "setsumei shite iru"], ["explained", "setsumei shita"]],
            [["plan", "keikaku"], ["planning", "keikaku suru"], ["plans", "keikaku suru"], ["planned", "keikaku shita"], ["", ""]],
            [["repeat", "kurikaesu"], ["repeats", "kurikaesu"], ["repeating", "kurikaesu"], ["repeated", "kurikaeshita"], ["", ""]],
            [["recycle", "saikuru"], ["recycles", "saikuru suru"], ["recycling", "saikuru suru"], ["recycled", "saikuru shita"], ["", ""]],
            [["defecate", "便秘する (benpi suru)"], ["defecates", "benpi suru"], ["defecating", "benpi suru"], ["", ""], ["", ""]],
            [["graduate", "sotsugyō suru"], ["graduates", "sotsugyō suru"], ["graduating", "sotsugyō shite iru"], ["graduated", "sotsugyō shita"], ["", ""]],
            [["tour", "tsūru"], ["tours", "tsūru"], ["touring", "tsūru"], ["toured", "tsūru shita"], ["", ""]],
            [["retire", "taishoku suru"], ["retiring", "taishoku suru"], ["retires", "taishoku suru"], ["", ""], ["", ""]],
            [["resign", "taishoku suru"], ["resigns", "taishoku suru"], ["resigned", "taishoku shita"], ["", ""], ["", ""]],
            [["exchange", "kōkan suru"], ["exchanges", "kōkan suru"], ["exchanging", "kōkan suru"], ["exchanged", "kōkan shita"], ["", ""]],
            [["confusion", ""], ["confusing", "konran sa seru"], ["confused", "konran shita"], ["", ""], ["", ""]],
            [["cycle", "saikuru"], ["cycles", "saikuru suru"], ["cycling", "saikuru shite iru"], ["cycled", "saikuru shita"], ["", ""]],
            [["relieve", "kyūkei suru"], ["relieves", "kyūkei suru"], ["relieving", "kyūkei shite iru"], ["", ""], ["", ""]],
            [["dictation", "dokusho"], ["dictates", "dokusho suru"], ["dictating", "dokusho shite iru"], ["dictated", "dokusho shita"], ["dictator", "dokusho"], ["dictated", "dokusho shita"]],
            [["joker", "jōkā"], ["joke", "jōku"], ["jokes", "jōku suru"], ["joking", "jōku shite iru"], ["joked", "jōku shita"]],
            [["research", "kenkyū"], ["researcher", "kenkyū-sha"], ["researches", "kenkyū suru"], ["researching", "kenkyū shite iru"], ["researched", "kenkyū shita"]],
            [["sweat", "ase"], ["sweats", "ase"], ["sweated", "ase o kaku"], ["", ""], ["", ""]],
            [["return", "kaeru"], ["returns", "kaeru"], ["returning", "kaette iru"], ["returned", "kaetta"], ["", ""]],
            [["buy", "kau"], ["buyer", "kōnyū-sha"], ["buying", "kau"], ["bought", "kaita"], ["", ""]],
            [["cry", "naku"], ["cries", "naku"], ["crying", "naite iru"], ["cried", "naita"], ["", ""]],
            [["swim", "oyogu"], ["swims", "oyogu"], ["swimming", "oyoide iru"], ["", ""], ["", ""]],
            [["laugh", "warau"], ["laughs", "warau"], ["laughing", "waraっている"], ["laughed", "waraった"], ["", ""]],
            [["telephone", "denwa suru"], ["telephones", "denwa suru"], ["telephoned", "denwa shita"], ["", ""], ["", ""]],
            [["long lasting", "nagaku tsuzuku"], ["", ""], ["", ""], ["", ""], ["", ""]],
            [["kick", "keru"], ["kicks", "keru"], ["kicking", "kette iru"], ["kicked", "kerita"], ["", ""]],
            [["range", "iki"], ["ranges", "iki"], ["ranging", "iki"], ["ranged", "iki"]],
            [["market", "sūpā"], ["marketing", "kōsō"], ["marketed", "kōsō shita"], ["", ""]],
            [["message", "メッセージ (messēji)"], ["messages", "messēji"], ["messaging", "messēji"], ["", ""]],
            [["shape", "katachi"], ["shapes", "katachi"], ["shaping", "katachi"], ["", ""]],
            [["weak", "yowai"], ["weakening", "yowaku naru"], ["weakened", "yowakunatta"], ["", ""]],
            [["kind", "shinsetsu"], ["kindly", "shinsetsu ni"], ["", ""]],
            [["serious", "shinkoku"], ["seriously", "shinkoku ni"], ["", ""]],
            [["anger", "ikari"], ["angrily", "ikari de"], ["angered", "ikareta"], ["", ""]],
            [["sink", "shizumu"], ["sinks", "shizumu"], ["sinking", "shizunde iru"], ["sank", "shizunda"], ["", ""]],
            [["insignificant", "sūki"], ["insignificantly", "sūki ni"], ["", ""]],
            [["casual", "kān"], ["casually", "kān ni"], ["", ""]],
            [["suspicious", "ayashii"], ["suspiciousness", "ayashisa"], ["suspiciously", "ayashiku"], ["", ""]],
            [["decision", "ketsudan"], ["decisions", "ketsudan"], ["decided", "ketsudanshita"], ["", ""]],
            [["great", "subarashii"], ["greatly", "subarashiku"], ["", ""]],
            [["truth", "shin"], ["true", "shinjitsu"], ["truly", "shin no"], ["", ""]],
            [["warmth", "atatakai"], ["warmly", "atatakai"], ["", ""]],
            [["gentle", "shinsetsu"], ["gently", "shinsetsu ni"], ["", ""], ["", ""], ["", ""]],
            [["part", "bun"], ["parts", "buns"], ["partially", "bunten-teki ni"], ["", ""], ["", ""]],
            [["suspense", "sasen"], ["suspensefully", "sasen ni"], ["", ""], ["", ""], ["", ""]],
            [["bitter", "naita"], ["bitterly", "naita ni"], ["", ""], ["", ""], ["", ""]],
            [["slim", "hosoi"], ["slims", "hosoi"], ["slimming", "hosoi"], ["", ""], ["", ""]],
            [["fully", "sukkiri"], ["fully", "sukkiri"], ["", ""], ["", ""], ["", ""]],
            [["narrow", "semai"], ["narrowingly", "semai"], ["narrowing", "semai"], ["", ""], ["", ""]],
            [["freeze", "furu"], ["freezes", "furu"], ["freezing", "furu"], ["", ""], ["", ""]],
            [["deeply", "fukai"], ["deep", "fukai"], ["", ""], ["", ""], ["", ""]],
            [["tighten", "kōsokasu"], ["tightly", "kōsokasu"], ["", ""], ["", ""], ["", ""]],
            [["beautiful", "utsukushii"], ["beautification", "utsukushiku suru"], ["beautifully", "utsukushiku"], ["beautified", "utsukushiku shita"], ["", ""]],
            [["plant", "shokubutsu"], ["planting", "shokubutsu o ueru"], ["plants", "shokubutsu"], ["planted", "shokubutsu o ueta"], ["", ""]],
            [["prescription", "yaku"], ["prescribing", "yaku"], ["prescribed", "yaku shita"], ["", ""]],
            [["staple", "hoji"], ["stapling", "hoji suru"], ["stapled", "hoji shita"], ["", ""]],
            [["bowl", "bōru"], ["bowling", "bōru suru"], ["", ""], ["", ""], ["", ""]],
            [["rock", "iwa"], ["rocking", "iwa o yureru"], ["rocks", "iwa"], ["rocked", "iwa o yureta"], ["", ""]],
            [["drum", "doramu"], ["drumming", "doramu suru"], ["drums", "doramu"], ["drummed", "doramu shita"], ["", ""]],
            [["picture", "e"], ["picturing", "e o kaku"], ["pictured", "e o kaita"], ["", ""]],
            [["bench", "benshu"], ["benching", "benshu suru"], ["benched", "benshu shita"], ["", ""]],
            [["sculpture", "chōkoku"], ["sculpturing", "chōkoku suru"], ["sculptured", "chōkoku shita"], ["", ""]]
    ];
    
    object = [
            [["book", "hon"]],
            [["tissue", "Soshiki"]],
            [["door", "doa"]],
            [["roof ", "yane"]],
            [["bookcase", "hondana"]],
            [["calculator ", "dentaku"]],
            [["cigar ", "Hamaki"]],
            [["kettle ", "yakan"]],
            [["rose", "bara"]],
            [["plant ", "shokubutsu"]],
            [["luggage", "nimotsu"]],
            [["wood", "mokuzai"]],
            [["tool", "Dōgu"]],
            [["rock", "ishi"]],
            [["medicine", "kusuri"]],
            [["fence", "saku"]],
            [["picture", "shashin"]],
            [["paintbrush", "efude"]],
            [["dictionary", "jisho"]],
            [["cash", "genkin"]],
            [["toy", "omocha"]],
            [["stairs", "kaidan"]],
            [["stone", "ishi"]],
            [["petal", "hanabira"]],
            [["rubber", "gomu"]],
            [["ice", "kori"]],
            [["chopsticks", "hashi"]],
            [["bandage", "hotai"]],
            [["smoke", "kemuri"]],
            [["japanese", "Nihongo"]],
            [["pencil", "enpitsu"]],
            [["eraser", "keshigomu"]],
            [["homework", "shukudai"]],
            [["key", "kagi"]],
            [["window", "mado"]],
            [["battery", "denchi"]],
            [["television", "terebi"]],
            [["lamp", "shomei"]],
            [["chair", "isu"]],
            [["toothbrush", "haburashi"]],
            [["wall", "kabe"]],
            [["bridge", "hashi"]],
            [["blanket", "mofu"]],
            [["textbook", "kyokasho"]],
            [["information", "joho"]],
            [["pillow", "makura"]],
            [["machine", "kikai"]],
            [["scissors", "hasami"]],
            [["table", "teburu"]],
            [["paper", "kami"]],
            [["map", "chizu"]],
            [["backpack", "ryukku"]],
            [["ruler", "jogi"]],
            [["money", "okane"]],
            [["scarf", "mafura"]],
            [["shoe", "kutsu"]],
            [["food", "tabemono"]],
            [["hat", "boshi"]],
            [["gloves", "tebukuro"]],
            [["wallet", "saifu"]],
            [["ring", "yubiwa"]],
            [["bag", "kaban"]],
            [["fire", "kaji"]],
            [["glasses", "megane"]],
            [["drawer", "hikidashi"]],
            [["clock", "tokei"]],
            [["clothes", "fuku"]],
            [["turtle", "kame"]],
            [["sunflower", "himawari"]],
            [["paint", "enogu"]],
            [["mirror", "kagami"]],
            [["diary", "nikki"]],
            [["ink", "sumi"]],
            [["cotton", "men"]],
            [["bleach ", "hyohakuzai"]],
            [["aluminium foil"]],
            [["microscope ", "kenbikyo"]],
            [["prescription ", "shohosen"]],
            [["rubber band", "gomubando"]],
            [["speaker", "supika"]],
            [["seaweed", "kaiso "]],
            [["stapler", "hotchikisu"]],
            [["bowl", "boru"]],
            [["pot", "nabe"]],
            [["guidebook", "ryoko gaidobukku"]],
            [["souvenir", "o-miyage"]],
            [["stove", "konro"]],
            [["musical instrument", "gakki"]],
            [["purse", "handobaggu"]],
            [["jewlry", "hoseki"]],
            [["football", "futtoboru"]],
            [["paper clip", "pepe kurippu"]],
            [["dishwasher", "shokkiaraiki"]],
            [["drums", "doramu"]],
            [["bottle", "bin"]],
            [["plastic", "purasutikku"]],
            [["bench", "benchi"]],
            [["sculpture", "chokoku"]],
            [["resume", "rireski-sho"]],
            [["mug", "magukappu"]],
            [["volleyball", "bareboru"]],
            [["passport", "pasupoto"]],
            [["plastic wrapper", "rappu"]],
            [["board game", "bodo gemu"]],
            [["compass", "konpasuu"]],
            [["trashcan", "gomibako"]],
            [["card", "kado"]],
            [["seat", "zaseki"]],
            [["spoon", "supun"]],
            [["fork", "foku"]],
            [["knife", "naifu"]],
            [["plate", "sara"]],
            [["cup", "kappu"]],
            [["drinking glass", "koppu"]],
            [["microwave oven", "denshi renji"]],
            [["photo", "shashin"]],
            [["refrigerator", "reizoko"]],
            [["computer", "kompuyta"]],
            [["air conditioner", "eakon"]],
            [["desk", "tsukue"]],
            [["laptop", "notopasokon"]],
            [["carpet", "kapetto"]],
            [["mat", "matto"]],
            [["furniture", "kagu"]],
            [["bed", "beddo"]],
            [["electric plug", "denki yo purago"]],
            [["radio", "rajio"]],
            [["sofa", "sofa"]],
            [["curtain", "katen"]],
            [["tape", "serotepu"]],
            [["makeup", "kesho"]],
            [["shaving razor", "higesori"]],
            [["towel", "taoru"]],
            [["soap", "sekken"]],
            [["toothpaste", "ha migakiko"]],
            [["shampoo", "shanpu"]],
            [["conditioner", "rinsu"]],
            [["deodrant", "deodoranto"]],
            [["whiteboard", "howaitobodo"]],
            [["pen", "pen"]],
            [["notebook", "noto"]],
            [["letter", "moji"]],
            [["mailbox", "yubin'uke"]],
            [["menu", "menyu"]],
            [["glue", "secchakuzai"]],
            [["chalk", "choku"]],
            [["phone number", "denwa bango"]],
            [["ticket", "kippu"]],
            [["suitcase", "susukesu"]],
            [["coin", "koka"]],
            [["sandal", "sandaru"]],
            [["trunk", "toranku"]],
            [["umberella", "kasa"]],
            [["cutting board", "manaita"]],
            [["medicine", "yakugaku"]],
            [["mattress", "Mattoresu"]],
            [["calendar", "karenda"]],
            [["camera", "kamera"]],
            [["remote control", "rimokon"]],
            [["gasoline", "gasorin"]],
            [["silk", "sjiruku"]],
            [["alligator", "wani"]],
            [["cobra", "kobura"]],
            [["parrot", "omu"]],
            [["qual", "uzura"]],
            [["duck", "kamo"]],
            [["peacock", "kujaku"]],
            [["falcon", "taka"]],
            [["shirt", "shatsu"]],
            [["swan", "hakucho"]],
            [["owl", "fukuro"]],
            [["penguin", "pengin"]],
            [["dandelion", "tanpopo"]],
            [["tulip", "churippu"]],
            [["lily", "yuri"]],
            [["lavendar", "rabenda"]],
            [["handball", "handoboru"]],
            [["blackboard", "kokuban"]],
            [["rope", "ropu"]],
            [["ball", "boru"]],
            [["ribbon", "ribon"]],
            [["keyboard", "kibodo"]],
            [["printer", "purinta"]]
    ];


     career = [
            [["teacher", "sensei"]],
            [["astronaut", "uchu hikoshi"]],
            [["mayor", "schicho"]],
            [["gardener", "Niwashi"]],
            [["priniciple", "kocho"]],
            [["programmer", "purogurama"]],
            [["veterinarian", "jui"]],
            [["soldier", "heishi"]],
            [["scientist", "kagakusha"]],
            [["String[][][]ruction worker", "kensetsu sagyoin"]],
            [["entrepeneur", "kigyoka"]],
            [["boy", "otoko no ko"]],
            [["waiter", "weita "]],
            [["customer", "o kyaku san"]],
            [["employee", "kaishain"]],
            [["team", "chimu"]],
            [["she", "kanojo"]],
            [["athelete", "supotsu senshu"]],
            [["vegeterian", "bejitarian"]],
            [["player", "sneshu"]],
            [["guest", "raikyaku"]],
            [["prime minister", "shuho"]],
            [["immigrant", "imin"]],
            [["occupation", "shokugyo"]],
            [["empress", "kogo"]],
            [["youth", "shoso"]],
            [["career", "kyaria"]],
            [["pastor", "bokushi"]],
            [["emperor", "kotei"]],
            [["carpetner", "takumi"]],
            [["salesperson", "hanbaiin"]],
            [["king", "o sama"]],
            [["prince", "oji"]],
            [["princess", "ojo"]],
            [["undergraduate", "gakubu gakusei"]],
            [["postgraduate", "daiigakuin sei"]],
            [["queen", "jo"]],
            [["freind", "tomo dachi"]],
            [["girl", "onna no ko"]],
            [["dentist", "haisha"]],
            [["they", "karera"]],
            [["monk", "shudoshi"]],
            [["together", "isshoni"]],
            [["teenage", "tineija"]],
            [["grandmother", "sobo"]],
            [["businessperson", "jitsugyoka"]],
            [["preist", "saishi"]],
            [["uncle", "oji"]],
            [["singer", "kashu"]],
            [["mother", "oka san"]],
            [["father", "oto san"]],
            [["grandfather", "oji san"]],
            [["husband", "oto"]],
            [["wife", "tsuma"]],
            [["son", "musuko"]],
            [["daughter", "musume"]],
            [["spouse", "haigusha"]],
            [["family", "kazoku"]],
            [["flight attendant", "kyakushitsu jomuin"]],
            [["nurse", "kangoshi"]],
            [["doctor", "isha"]],
            [["mailman", "yubin ya san"]],
            [["recipient", "uketorinink"]],
            [["interpreter", "tsuyaku"]],
            [["translator", "hon'yakuka"]],
            [["accountant", "kaikeishi"]],
            [["lawyer", "bengoshi"]],
            [["boss", "joshi"]],
            [["coworker", "doryo"]],
            [["woman", "onna no hito"]],
            [["man", "otoko no hito"]],
            [["girlfreind", "kanojo"]],
            [["boyfriend", "kareshi"]],
            [["clerk", "ten in"]],
            [["child", "kodomo"]],
            [["neighbour", "rinjin"]],
            [["police officer", "keisatsukan"]],
            [["office worker", "kaishain"]],
            [["farmer", "noka"]],
            [["housewife", "shufu"]],
            [["factory worker", "koin"]],
            [["engineer", "enjina"]],
            [["president", "daitoryo"]],
            [["firefighter", "shoboshi"]],
            [["secretary", "hisho"]],
            [["manager", "maneja"]],
            [["her", "kanojo no"]],
            [["relatives", "shinzoku"]],
            [["aunt", "oba san"]],
            [["driver", "untenshu"]],
            [["chef", "shefu"]],
            [["student", "seito"]],
            [["professor", "kyoju"]],
            [["library", "toshokan"]],
            [["conductor", "shasho"]],
            [["group", "dantai"]],
            [["tourist", "ryokosha"]],
            [["reporter", "kisha"]],
            [["pilot", "sojushi"]],
            [["person", "ningen"]],
            [["adult", "otona"]],
            [["baby", "aka chan"]],
            [["innocent", "Mujitsu no"]],
            [["kindergarten", "yochien"]],
            [["doctorate", "hakase"]],
            [["painter", "gaka"]],
            [["politician", "seijika"]],
            [["musician", "ongaku ka"]],
            [["judge", "sainbankan "]],
            [["investigation", "sosa"]]
    ];


    environment = [
            [["toilet", "toire"]],
            [["room", "heya"]],
            [["house", "ie"]],
            [["park", "koen"]],
            [["city", "machi"]],
            [["floor", "yuka"]],
            [["marketing", "maketingu"]],
            [["museum", "bijutsukan"]],
            [["aquiarum", "Suizokukan"]],
            [["sale", "seru"]],
            [["thunderstorm", "raiu"]],
            [["golf", "gorufu"]],
            [["camping", "kyanpu"]],
            [["farm", "nojo"]],
            [["country", "kuni"]],
            [["soil", "dojo"]],
            [["sunrise", "hinode"]],
            [["sunset", "yuhi"]],
            [["land", "tochi"]],
            [["stadium", "sutajiamu"]],
            [["home", "ie"]],
            [["place", "tokoro"]],
            [["nature", "shizen"]],
            [["environment", "kankyo"]],
            [["country side", "inaka"]],
            [["castle", "shiro"]],
            [["garbage", "gomi"]],
            [["sand", "suna"]],
            [["garage", "gareji"]],
            [["disaster", "saigai"]],
            [["pollution", "osen"]],
            [["rain", "ame ga furu"]],
            [["pyramid", "pirimiddo"]],
            [["habitat", "shukan"]],
            [["air", "kuki"]],
            [["moon", "tsuki"]],
            [["hill", "oka"]],
            [["mainland", "hondo"]],
            [["mountain", "yama"]],
            [["beach", "hama"]],
            [["island", "shima"]],
            [["forest", "mori"]],
            [["river", "kawa"]],
            [["ocean", "umi"]],
            [["lake", "mizuumi"]],
            [["living room", "ima"]],
            [["dinning room", "dainingurmu"]],
            [["hallway", "roka"]],
            [["backyard", "uraniwa"]],
            [["room", "heya"]],
            [["emergency room", "kinkyu chiryoshitsu"]],
            [["insurance", "hoken"]],
            [["lobby", "robi"]],
            [["post office", "yubinkyoku"]],
            [["leaf", "ha"]],
            [["tree", "ki"]],
            [["grass", "shibafu"]],
            [["flower", "hana"]],
            [["bush", "shiegemi"]],
            [["elementary school", "shogakko"]],
            [["middle school", "chugakko"]],
            [["highschool", "koko"]],
            [["university", "daigaku"]],
            [["college", "daigaku"]],
            [["apartment", "apatok"]],
            [["gym", "taiikukan"]],
            [["vacation", "kyuka"]],
            [["winter", "fuyu"]],
            [["summer", "natsu"]],
            [["spring", "haru"]],
            [["birthday", "tanjobi"]],
            [["fetival", "matsuri"]],
            [["mall", "shoppingmoru"]],
            [["marathon", "marason"]],
            [["soccer", "sakka"]],
            [["basketball", "baskuttoberu"]],
            [["tower", "to"]],
            [["road", "michi"]],
            [["traffic jam", "jutai"]],
            [["house", "ie"]],
            [["building", "tatemono"]],
            [["lesson", "jugyo"]],
            [["rent", "kariru"]],
            [["subway", "chikatetsu"]],
            [["escalator", "esukareta"]],
            [["timetable", "jikokuhyo"]],
            [["bank", "ginko"]],
            [["rain", "ame"]],
            [["snow", "yuki"]],
            [["cloud", "kumo"]],
            [["flood", "kozui"]],
            [["typhoon", "taifu"]],
            [["weather report", "tenki yoho"]],
            [["sky", "sora"]],
            [["sunny", "hareta"]],
            [["rainbow", "niji"]],
            [["temperature", "ondo"]],
            [["humid", "shimetta"]],
            [["windy", "kane no tsuyoi"]],
            [["fog", "kiri"]],
            [["hurricane", "hariken"]],
            [["company", "kaisha"]],
            [["torndao", "tatusmaki"]],
            [["office", "ofisu"]],
            [["earth", "chikyu"]],
            [["temple", "otera"]],
            [["mosque", "mosuku"]],
            [["church", "kyokai"]],
            [["statue", "zo"]],
            [["waterfall", "taki"]],
            [["palace", "kyuden"]],
            [["garden", "niwa"]],
            [["economics", "keizaigaku"]],
            [["education", "kyoiku"]],
            [["party", "pati"]],
            [["funeral", "sogi"]],
            [["store", "mise"]],
            [["weather", "tenki"]],
            [["restaurant", "restoran"]],
            [["bar", "ba"]],
            [["drought", "hideri"]],
            [["hospital", "byoin"]],
            [["pharmacy", "yakkyoku"]],
            [["police stastion", "keisatsusho"]],
            [["dangerous", "kiken"]],
            [["classroom", "kyoshitsu"]],
            [["sun", "taiyo"]],
            [["planet", "wakusei"]],
            [["amusement park", "yuenchi"]],
            [["zoo", "dobutsuen"]],
            [["fountain", "funsui"]],
            [["pool", "puru"]],
            [["hot spring", "onsen"]],
            [["aquarium", "suizokukan"]],
            [["picnic", "pikunikku"]],
            [["sport", "spotsu"]],
            [["diving ", "daibingu"]],
            [["boxing", "bokushingu"]],
            [["softball", "Sofutobōru"]],
            [["racing", "kyoso"]],
            [["movie theatre", "eigakan"]],
            [["karaoke", "karoake"]],
            [["music", "ongaku"]],
            [["literature", "bungaku"]],
            [["school", "gakko"]],
            [["exhibition", "tenrankai"]],
            [["government", "seifu"]],
            [["artihmetic", "sansu"]],
            [["physics", "butsurigaku"]],
            [["biology", "seibutsugaku"]],
            [["history", "rekishi"]],
            [["physical education", "taiiku"]],
            [["philospophy", "tetsugaku"]],
            [["psychology", "shinrigaku"]],
            [["sociology", "shakaigaku"]],
            [["biotechnology", "Baiotekunorojī"]],
            [["taosim", "dokyo"]],
            [["cancel", "torikesu"]],
            [["election", "senkyo"]]
    ];


     position = [
            [["here", "koko"]],
            [["there", "Soko ni wa"]],
            [["under", "shita"]],
            [["there", "soko"]],
            [["near", "chikai"]],
            [["high", "takai"]],
            [["low", "hikui"]],
            [["middle", "mannaka"]],
            [["up", "ue ni"]],
            [["top", "teppen"]],
            [["down", "shita ni"]],
            [["far", "tooi"]],
            [["that", "sono"]],
            [["corner", "kado"]],
            [["abroad", "kaigai de"]],
            [["address", "jusho"]],
            [["front", "mae"]],
            [["side", "yoko"]],
            [["east", "higashi"]],
            [["west", "nishi"]],
            [["north", "kita"]],
            [["south", "minami"]],
            [["outside", "soto"]],
            [["inside", "naka"]],
            [["towards", "ni mukatte"]],
            [["close", "shimeru"]],
            [["before", "mae ni"]],
            [["after", "no ato"]],
            [["sidewalk", "hodo"]],
            [["intersection", "kosaten"]],
            [["entrance", "iriguchi"]],
            [["direction", "michijun"]],
            [["guide", "gaido"]],
            [["exit", "deguchi"]],
            [["left", "hidari"]]
    ];


     time = [
            [["afternoon", "Gogo"]],
            [["sunrise", "Hinode"]],
            [["sunset", "Nichibotsu"]],
            [["time", "jikan"]],
            [["morning", "asa"]],
            [["always", "itsumo"]],
            [["often", "yoku"]],
            [["usually", "fudan"]],
            [["date", "deto"]],
            [["night", "ban"]],
            [["soon", "chikai uchi ni"]],
            [["later", "atode"]],
            [["month", "tsuki"]],
            [["weeknend", "shumastsu"]],
            [["semester", "gakki"]],
            [["week", "shu"]],
            [["year", "toshi"]],
            [["second", "byo"]],
            [["hour", "jikan"]],
            [["minutes", "fun"]],
            [["noon", "shogo"]],
            [["midnight", "mayonaka"]],
            [["evening", "yoru"]],
            [["sometimes", "tokidoki"]],
            [["never", "zenzen nai"]],
            [["now", "ima"]],
            [["today", "kyo"]],
            [["tomorrow", "ashita"]],
            [["yesterday", "kino"]],
            [["past", "kako"]],
            [["future", "shorai"]],
            [["departure", "shuppatsu"]],
            [["during", "Sonoaida"]]
    ];

     stuff = [
            [["bill", "seikyusho"]],
            [["price", "Kakaku"]],
            [["cost", "Ryōkin"]],
            [["birth", "tanjo"]],
            [["calorie", "karorii"]],
            [["energy", "Enerugī"]],
            [["carbohydrate", "tansuikabutsu"]],
            [["smoke", "Kemuri"]],
            [["geography", "chiri"]],
            [["chemistry", "kagaku"]],
            [["math", "sugaku"]],
            [["economy", "keizai"]],
            [["art", "bijutsu"]],
            [["bath", "o-furo"]],
            [["name", "shimei"]],
            [["price", "nedan"]],
            [["meal", "shokuji"]],
            [["shower", "shwa o abiru"]],
            [["world", "sekai"]],
            [["rectangle", "chohokei"]],
            [["dirt", "tsuchi"]],
            [["mail", "yubinbutsu"]],
            [["sqaure", "hiroba"]],
            [["agenda", "kadai"]],
            [["word", "kotoba"]],
            [["sound", "oto"]],
            [["energy", "enerugi"]],
            [["reason", "riyu"]],
            [["thing", "mono"]],
            [["circle", "en"]],
            [["gallery", "gyrari"]],
            [["noise", "zatsuon"]],
            [["game", "gemu"]],
            [["science", "kagaku"]],
            [["nationality", "kokuseki"]],
            [["square", "masume"]],
            [["octagon", "hakkakukei"]],
            [["finance", "kon yakusha"]],
            [["message", "messeji"]],
            [["number", "kazu"]],
            [["illegal", "iho"]],
            [["challange", "chosen"]],
            [["suprise", "odoroki"]],
            [["color", "iro"]],
            [["hexagon// rokkakkei"]],
            [["sphere", "tama"]],
            [["cube", "rippotai"]],
            [["shape", "Katachi"]]
    ];

    description =

            [
                    [["cold", "tsumetai"]],
                    [["weak", "yowai"]],
                    [["wave", "nami"]],
                    [["bad", "warui"]],
                    [["delicious", "oishii"]],
                    [["dirty", "kitanai"]],
                    [["nice", "Nīsu"]],
                    [["beautiful"]],
                    [["handsome", "hansamu"]],
                    [["kind", "shinsetsu"]],
                    [["serious", "majime"]],
                    [["ugly", "minikui"]],
                    [["easy", "kantan"]],
                    [["angry", "okotte iru"]],
                    [["scared", "kowai"]],
                    [["painful", "itai"]],
                    [["sink", "senmendai"]],
                    [["silver", "gin"]],
                    [["heatlh", "kenko"]],
                    [["insignificant", "taishita koto ga nai"]],
                    [["bright", "akarui"]],
                    [["disgusting", "mazui"]],
                    [["dark", "koi"]],
                    [["close", "chikai"]],
                    [["poor", "binbo"]],
                    [["winner", "shosha"]],
                    [["casual", "keishikibaranai"]],
                    [["famous", "yumei"]],
                    [["correct", "naosu"]],
                    [["tired", "tsukareta"]],
                    [["win", "katsu"]],
                    [["suspicious", "ayashii"]],
                    [["complete", "sumasu"]],
                    [["free", "muryo no"]],
                    [["deciscion", "kettei"]],
                    [["reality", "genjitsu"]],
                    [["private", "shiritsu no"]],
                    [["true", "shin no"]],
                    [["great", "zekkocho"]],
                    [["warm", "atatakai"]],
                    [["fat", "shibo"]],
                    [["mistake", "misu"]],
                    [["awesome", "sugoi"]],
                    [["rich yufuku-naba"]],
                    [["stupid", "oroka na"]],
                    [["attractive", "miryokuteki na"]],
                    [["part", "bubun"]],
                    [["fresh", "shinsen na"]],
                    [["pack", "tsumekomo"]],
                    [["suspense", "sasupensu"]],
                    [["thin", "usui"]],
                    [["skinny", "yasete iru"]],
                    [["salty", "shiokarai"]],
                    [["sweet", "amai"]],
                    [["bitter", "nigai"]],
                    [["short", "se ga hikui"]],
                    [["spicy", "karai"]],
                    [["tall", "se ga takai"]],
                    [["sour", "suppai"]],
                    [["slim", "surimu"]],
                    [["hungry", "o naka ga suku"]],
                    [["thristy", "nodo ga kawaku"]],
                    [["full", "o naka ga ippai"]],
                    [["round", "marui"]],
                    [["big", "okii"]],
                    [["small", "chiisai"]],
                    [["narrow", "semai"]],
                    [["hard", "katai"]],
                    [["long", "nagai"]],
                    [["busy", "isogashii"]],
                    [["roundabout", "kanjo kosaten"]],
                    [["freeze", "koru"]],
                    [["cloudy", "kumotta"]],
                    [["good", "yoi"]],
                    [["deep", "fukai"]],
                    [["shallow", "asai"]],
                    [["loose", "bukabuka"]],
                    [["hot", "atsui"]],
                    [["cool", "suzushii"]],
                    [["fluffy", "Fuwafuwa"]],
                    [["tight", "kitsui"]],
                    [["beautifull", "kirei"]],
                    [["strong", "tsuyoi"]],
                    [["elegant", "johin"]],
                    [["cute", "kawaii"]],
                    [["dull", "Nibui"]],
                    [["soft", "yawarakai"]],
                    [["kinds", "shurui"]],
                    [["famous", "Yūmeina"]],
                    [["safe", "anzen"]]
            ];


     animal = [
            [["pet", "petto"]],
            [["ant", "ari"]],
            [["vulture", "hagetaka"]],
            [["walrus", "seiuchi"]],
            [["giraffe", "kirin"]],
            [["cheetah", "chita"]],
            [["hippo", "kaba"]],
            [["crocodile", "wani"]],
            [["buffalo", "baffaro"]],
            [["eel", "unagi"]],
            [["guinea pig", "morumotto"]],
            [["crow", "karasu"]],
            [["jaguar", "jag"]],
            [["animal", "dobutsu"]],
            [["squid", "ika"]],
            [["fish", "sakana"]],
            [["nail", "tsume"]],
            [["insect", "konchu"]],
            [["camel", "rakuda"]],
            [["bird", "tori"]],
            [["dog", "inu"]],
            [["cat", "neko"]],
            [["mouse", "nezumi"]],
            [["cockroach", "gokiburi"]],
            [["mosquito", "ka"]],
            [["bee", "hachi"]],
            [["spider", "kumo"]],
            [["frog", "kareu"]],
            [["cow", "ushi"]],
            [["pig", "buta"]],
            [["sheep", "hitsuji"]],
            [["goat", "yagi"]],
            [["rabbit", "usagi"]],
            [["horse", "uma"]],
            [["snake", "hebi"]],
            [["crab", "kani"]],
            [["octopus", "tako"]],
            [["pigeon", "hato"]],
            [["elephant", "zo"]],
            [["fox", "kitsune"]],
            [["deer", "shika"]],
            [["lion", "raion"]],
            [["bear", "kuma"]],
            [["panda", ""]],
            [["whale", "kujira"]],
            [["dolphin", "iruka"]],
            [["tiger", "tora"]],
            [["monkey", "saru"]],
            [["zebra", "shimauma"]],
            [["leopard", ""]],
            [["koala", "koara"]],
            [["kangaroo", "kangroo"]],
            [["rhinoceros", "sai"]],
            [["squirrel", "risu"]],
            [["bat", "komori"]],
            [["wolf", "okami"]],
            [["orangutan //"]],
            [["gorilla", "gorira"]],
            [["chimpanzee", "chinpanji"]],
            [["sloth", ""]],
            [["anteater", "arikui"]],
            [["porcupine "]],
            [["raccoon", "araiguma"]],
            [["hyena", "haiena"]],
            [["snail", ""]],
            [["cicada", "semi"]],
            [["butterfly", "cho"]],
            [["ladybug", "tentomushi"]],
            [["dragonfly", ""]],
            [["grasshopper "]],
            [["firefly", "hotaru"]],
            [["worm", "mimizu"]],
            [["shark", "same"]],
            [["jellyfish", "kurage"]]
    ];

    body = [
            [["liver", "kanzo"]],
            [["knee", "hiza"]],
            [["heart", "shinzo"]],
            [["brain", "no"]],
            [["hand", "bursagaru"]],
            [["back", "senaka"]],
            [["lip", "kuchibiru"]],
            [["soul", "tamashii"]],
            [["memory", "kokuryoku"]],
            [["muscle", "kinniku"]],
            [["bone", "hone"]],
            [["face", "kao"]],
            [["head", "atama"]],
            [["ear", "mimi"]],
            [["chin", "ago"]],
            [["forehead", "hitai"]],
            [["mouth", "kuchi"]],
            [["hair", "kami"]],
            [["mutsatche", "kuchihige"]],
            [["beard", "agohige"]],
            [["cheeck", "hoho"]],
            [["neck", "kubi"]],
            [["thigh", "momo"]],
            [["calf", "fukurahagi"]],
            [["ankle", "ashikubi"]],
            [["waist", "koshi"]],
            [["nose", "hana"]],
            [["tooth", "ha"]],
            [["eyelash", "matsuge"]],
            [["eye", "me"]],
            [["eyebrow", "mayuge"]],
            [["eyelid", "mabuta"]],
            [["tongue", "shita"]],
            [["saliva", "tsuba"]],
            [["tear", "namida"]],
            [["shoulder", "kata"]],
            [["arm", "ude"]],
            [["elbow", "hiji"]],
            [["forearm", "zenwan"]],
            [["wrist", "tekubi"]],
            [["hand", "te"]],
            [["finger", "yubi"]],
            [["pinkie", "koyobi"]],
            [["index finger", "hitisashiyubi"]],
            [["rib", "abara"]],
            [["belly", "fukubu"]],
            [["kidney", "jinzo"]],
            [["shoulderblade", "kenkokotsu"]],
            [["thumb", "oyayubi"]],
            [["lung", "hai"]],
            [["stomach", "i"]],
            [["leg", "ashi"]],
            [["chest", "mune"]],
            [["skin", "hada"]],
            [["blood", "ketsueki"]]
    ];


     clothing =
            [
                    [["trousers", "Zubon"]],
                    [["shirt ", "Shatsu"]],
                    [["shoes", "Kutsu"]],
                    [["skirt", "Sukāto"]],
                    [["vest", "besuto"]],
                    [["necktie", "nekutai"]],
                    [["dress", "doresu"]],
                    [["sleeve", "sode"]],
                    [["shorts", "shoto pantsu"]],
                    [["jacket", "jakketo"]],
                    [["torso", "do"]],
                    [["underwear", "shitagi"]],
                    [["suit", "sutsu"]],
                    [["undershirt", "hadagi"]],
                    [["sweater", "seta"]],
                    [["swimsuit", "mizugi"]],
                    [["jeans", "jinzu"]],
                    [["pajamas", "pajama"]],
                    [["sock", "kutsushita"]],
                    [["pants", "zubon"]]
            ];


     feeling = [
            [["happy", "Happī"]],
            [["sad", "Kanashī"]],
            [["shy", "hazukashii"]],
            [["want", "hoshii"]],
            [["intrested", "kyomi ga aru"]],
            [["bored", "taikutsu shita"]],
            [["embarassed", "hazukashigaru"]],
            [["job", "shigoto"]],
            [["trip", "ryoko"]],
            [["feeling", "kibun"]],
            [["promise", "yakusoku"]],
            [["greeting", "aisatsu"]],
            [["well", "yoku"]],
            [["behaivior", "koi"]],
            [["romantic", "romanchikku"]],
            [["fine", "genki"]],
            [["experience", "keiken"]],
            [["rest", "yasumu"]],
            [["humble", "kenkyo na"]],
            [["nap", "hirune"]],
            [["happy", "ureshii"]]

    ];

     food = [
            [["salad", "sarada"]],
            [["apple", "ringo"]],
            [["orange", "orenji iro"]],
            [["pizza", "piza"]],
            [["egg", "tamago"]],
            [["noodle", "ramen"]],
            [["raspberry", "razuberi"]],
            [["pepper", "kosho"]],
            [["tuna fish", "maguro"]],
            [["basil", "bejuru"]],
            [["sardine", "iwashi"]],
            [["soup", "supu"]],
            [["water", "mizu"]],
            [["coffee", "kohi"]],
            [["soda", "tansan inryo"]],
            [["milk", "gyunyu"]],
            [["tea", "cha"]],
            [["garlic", "ninniku"]],
            [["ginger", "shoga"]],
            [["sugar", "sato"]],
            [["salt", "shio"]],
            [["olive oil", "oribu oiru"]],
            [["sauce", "sosu"]],
            [["vinegar", "su"]],
            [["rice", "kome"]],
            [["wheat", "mugi"]],
            [["corn", "tomorokoshi"]],
            [["butter", "bata"]],
            [["bread", "pan"]],
            [["potato", "jagaimo"]],
            [["soybean", "daizu"]],
            [["barley", "omugi"]],
            [["fruit", "kudamono"]],
            [["apricot", "anzu"]],
            [["banana", "banana"]],
            [["grape", "budo"]],
            [["watermelon", "suika"]],
            [["grapefruit", "grapefurtsu"]],
            [["pineapple", "painappuru"]],
            [["melon", "meron"]],
            [["nut", "nattsu"]],
            [["peanut", "pinattsu"]],
            [["cashew nuts", "kasunattsu"]],
            [["vegetable", "yasai"]],
            [["carrot", "ninjin"]],
            [["turnip", "kabu"]],
            [["onion", "tamenegi"]],
            [["mushroom", "kinoko"]],
            [["tomato", "tomato"]],
            [["lettuce", "retasu"]],
            [["seafood", "gyokai-rui"]],
            [["shrimp", "ebi"]],
            [["salmon", "sake"]],
            [["meat", "niku"]],
            [["beef", "gyu niku"]],
            [["pork", "buta niku"]],
            [["chicken", "tori niku"]],
            [["lamb", "ramu niku"]],
            [["sweets", "o kashi"]],
            [["breakfast", "asagohab"]],
            [["lunch", "chushoku"]],
            [["dinner", "yushoku"]],
            [["snack", "o-kashi"]],
            [["pumpkin", "kabocha"]],
            [["lobster", "robusuta"]],
            [["cauliflower", "kaurifurwa"]],
            [["cabbage", "kyabestu"]],
            [["celery", "serori"]],
            [["chilli pepper", "togarashi"]],
            [["eggplant", "nasu"]],
            [["brocolli", "burokkori"]],
            [["spinach", "horesno"]],
            [["bean sprout", "moyashi"]],
            [["cheese", "hizu"]],
            [["strawberry", "ichigo"]],
            [["fig", "ichijiku"]],
            [["plum", "puramu"]],
            [["lemon", "remon"]],
            [["blueberry", "buruberu"]],
            [["prune", "purun"]],
            [["peach", "momo"]],
            [["ice cream", "aisukurimu"]],
            [["chocolate", "chokoreto"]],
            [["juice", "jusu"]],
            [["soy sauce", "shoyu"]],
            [["sesame", ""]],
            [["oil", "abura"]],
            [["sausage", "chozume"]],
            [["cherry", "sukuranbo"]],
            [["hamburger", "hanbaga"]]
    ];


     personal =
            [
                    [["bye", "sayonara"]],
                    [["okay", "oke"]],
                    [["lame", "tsumaranai"]],
                    [["kind", "shurui"]],
                    [["death", "chokaku shogaisha"]],
                    [["liar", "usotsuki"]],
                    [["afraid", "kowai"]],
                    [["healthy", "kenko teki"]],
                    [["satisfied", "manzoku shita"]],
                    [["sad", "kanashii"]],
                    [["calm", "ochitsuita"]],
                    [["boring", "tsumaranai"]],
                    [["exciting", "shigeki teki"]],
                    [["fear", "osoreru"]],
                    [["feel", "kanjiru"]],
                    [["pain", "itami"]],
                    [["nervous", "fuan ni naru"]],
                    [["taste", "aji"]],
                    [["infection", "kansen"]],
                    [["sick", "guai ga warui"]],
                    [["nausea", "hakike"]],
                    [["asthma", "zensoku"]],
                    [["itch", "kayumi"]],
                    [["clever", "kashikoi"]],
                    [["honest", "seijutsu"]],
                    [["sprain", "hineru"]],
                    [["funny", "omoshiroi"]],
                    [["dissatisfied", "fuman"]],
                    [["difficult", "muzukashii"]],
                    [["sleepy", "nemui"]],
                    [["introverted", "naikoteki"]],
                    [["extroverted", "gaikoteki"]],
                    [["proactive", "Sekigyokuteki"]],
                    [["smart", "kashikoi"]],
                    [["scary", "kowai"]],
                    [["brave", "yukan"]],
                    [["hobby", "shumi"]],
                    [["caution", "Chūi"]]
            ];


     sentence_words = [
            [["you", "anata"]],
            [["by", "ni yotte"]],
            [["to", "e"]],
            [["be", "aru"]],
            [["in", "nai"]],
            [["the", "その (sono)"]],
            [["made", "tsukutta"]],
            [["a", "ichi"]],
            [["we", "watashitachi"]],
            [["live", "ikiru"]],
            [["on", "ni"]],
            [["it", "sore"]],
            [["took", "totta"]],
            [["come", "kuru"]],
            [["again", "mata"]],
            [["she", "kanojo"]],
            [["does", "suru"]],
            [["not", "nai"]],
            [["is", "da"]],
            [["usually", "yoku"]],
            [["don't", "shinai"]],
            [["look", "miru"]],
            [["looks", "miru"]],
            [["these", "kore"]],
            [["aren't", "janai"]],
            [["has", "aru"]],
            [["finish", "owaru"]],
            [["finished", "owatta"]],
            [["finishing", "owatte iru"]],
            [["who", "dare"]],
            [["will", "suru"]],
            [["after", "ato"]],
            [["your", "anata no"]],
            [["aren't", "dewa nai"]],
            [["he", "kare"]],
            [["wants", "hoshii"]],
            [["see", "miru"]],
            [["those", "sore"]],
            [["theirs", "kare-ra no"]],
            [["to", "e"]],
            [["wonder", "kangaeru"]],
            [["if", "moshi"]],
            [["she", "kanojo"]],
            [["will", "suru"]],
            [["ask", "tazuneru"]],
            [["where", "doko"]],
            [["my", "watashi no"]],
            [["im", "boku wa"]],
            [["from", "kara"]],
            [["can", "dekiru"]],
            [["just", "tada"]],
            [["were", "datta"]],
            [["with", "to"]],
            [["anyone", "dareka"]],
            [["wish", "negau"]],
            [["could", "dekita"]],
            [["have", "aru"]],
            [["has", "aru"]],
            [["doesn't", "nai"]],
            [["did", "shita"]],
            [["didn't", "shinakatta"]],
            [["forgot", "wasureta"]],
            [["they", "karera"]],
            [["us", "watashitachi"]],
            [["take", "toru"]],
            [["seem", "mi-eru"]],
            [["an", "ichi"]],
            [["and", "to"]],
            [["therefore", "yotei"]],
            [["so", "dakara"]],
            [["then", "sorekara"]],
            [["would", "darou"]],
            [["like", "suki"]],
            [["back", "kaerimasu"]],
            [["return", "kaeru"]],
            [["saw", "mita"]],
            [["seen", "mito"]],
            [["will", "suru"]],
            [["all", "subete"]],
            [["are", "da"]],
            [["there", "soko"]],
            [["pair", "tsui"]],
            [["someone", "dareka"]],
            [["know", "shiru"]],
            [["them", "karera"]],
            [["thinking", "kangaete iru"]],
            [["thought", "kangaeta"]],
            [["though", "soredemo"]],
            [["however", "shikashi"]],
            [["if", "moshi"]],
            [["would", "darou"]],
            [["better", "yoi"]],
            [["may", "kamoshirenai"]],
            [["burrow", "horu"]],
            [["collecting", "atsumeru"]],
            [["at", "de"]],
            [["way", "kata"]],
            [["let's", "shiyou"]],
            [["understand", "wakaru"]],
            [["either", "ika"]],
            [["neither", "mo"]],
            [["answer", "kotae"]],
            [["got", "te ni ireru"]],
            [["where", "doko"]],
            [["take", "toru"]],
            [["anything", "nanika"]],
            [["that's", "sore wa"]],
            [["we", "watashi-tachi"]],
            [["want", "hoshii"]],
            [["know", "shiru"]],
            [["whose", "dare no"]],
            [["asked", "tazunemashita"]],
            [["likes", "suki"]],
            [["here's", "koko ni"]],
            [["some", "ikutsu"]],
            [["long", "nagai"]],
            [["left", "sagashi"]],
            [["me", "watashi"]],
            [["note", "memo"]],
            [["acknowledged", "ninshiki shita"]],
            [["lost", "ushinatta"]],
            [["found", "mitsukemashita"]],
            [["usually", "yoku"]],
            [["before", "mae"]],
            [["send", "okuru"]],
            [["sent", "okurimashita"]],
            [["were", "deshita"]],
            [["was", "deshita"]],
            [["often", "yoku"]],
            [["just", "tada"]],
            [["behind", "ushiro"]],
            [["happened", "okita"]],
            [["happen", "okiru"]],
            [["happening", "okite iru"]],
            [["happens", "okiru"]],
            [["an", "ichi"]],
            [["peel", "moru"]],
            [["went", "itta"]],
            [["learn", "manabu"]],
            [["else", "hoka"]],
            [["none", "nani mo nai"]],
            [["nothing", "nanimo"]],
            [["almost", "hotondo"]],
            [["reason", "riyu"]],
            [["never", "kesshite"]],
            [["wish", "negai"]],
            [["having", "motte iru"]],
            [["tried", "tameshita"]],
            [["try", "tamesu"]],
            [["something", "nanika"]],
            [["began", "hajimeta"]],
            [["dropped", "ochita"]],
            [["pass", "passu"]],
            [["out", "soto"]],
            [["order", "chūmoku"]],
            [["went", "itta"]],
            [["do", "suru"]],
            [["early", "hayai"]],
            [["must", "bikō"]],
            [["still", "mada"]],
            [["get", "toru"]],
            [["glad", "ureshii"]],
            [["necessarily", "hitsuyō"]],
            [["reliable", "shinrai"]],
            [["mind", "kokoro"]],
            [["new", "atarashii"]],
            [["live", "ikiru"]],
            [["lived", "ikite ita"]],
            [["sense", "kan"]],
            [["check", "chekku"]],
            [["terribly", "hijō ni"]]
    ];

     transportation = [
            [["bike", ""]],
            [["car", "kuruma"]],
            [["train", "densha"]],
            [["airplane", ""]],
            [["truck", "torakku"]],
            [["boat", "fune"]],
            [["ship", ""]],
            [["jet", "jetto ki"]],
            [["airport", "kuko"]],
            [["station", "eki"]],
            [["train", "densha"]],
            [["bus", "basu"]],
            [["bicycle", "jitensha"]],
            [["car", "kurama"]],
            [["passenger", "jokyaku"]],
            [["bus stop", "basu tei"]]
    ];

     pluralfood = [
            [["salads", "sarada"]],
            [["apples", "ringo"]],
            [["oranges", "orenji iro"]],
            [["pizzas", "piza"]],
            [["eggs", "tamago"]],
            [["noodles", "ramen"]],
            [["raspberries", "razuberi"]],
            [["peppers", "kosho"]],
            [["tuna fish", "maguro"]],
            [["basil", "bejuru"]],
            [["sardines", "iwashi"]],
            [["soups", "supu"]],
            [["water", "mizu"]],
            [["coffees", "kohi"]],
            [["sodas", "tansan inryo"]],
            [["milk", "gyunyu"]],
            [["teas", "cha"]],
            [["garlic", "ninniku"]],
            [["ginger", "shoga"]],
            [["sugar", "sato"]],
            [["salt", "shio"]],
            [["olive oils", "oribu oiru"]],
            [["sauces", "sosu"]],
            [["vinegars", "su"]],
            [["rices", "kome"]],
            [["wheats", "mugi"]],
            [["corns", "tomorokoshi"]],
            [["butters", "bata"]],
            [["breads", "pan"]],
            [["potatoes", "jagaimo"]],
            [["soybeans", "daizu"]],
            [["barleys", "omugi"]],
            [["fruits", "kudamono"]],
            [["apricots", "anzu"]],
            [["bananas", "banana"]],
            [["grapes", "budo"]],
            [["watermelons", "suika"]],
            [["grapefruits", "grapefurtsu"]],
            [["pineapples", "painappuru"]],
            [["melons", "meron"]],
            [["nuts", "nattsu"]],
            [["peanuts", "pinattsu"]],
            [["cashew nuts", "kasunattsu"]],
            [["vegetables", "yasai"]],
            [["carrots", "ninjin"]],
            [["turnips", "kabu"]],
            [["onions", "tamanegi"]],
            [["mushrooms", "kinoko"]],
            [["tomatoes", "tomato"]],
            [["lettuces", "retasu"]],
            [["seafood", "gyokai-rui"]],
            [["shrimps", "ebi"]],
            [["salmons", "sake"]],
            [["meats", "niku"]],
            [["beefs", "gyu niku"]],
            [["porks", "buta niku"]],
            [["chickens", "tori niku"]],
            [["lambs", "ramu niku"]],
            [["sweets", "o kashi"]],
            [["breakfasts", "asagohab"]],
            [["lunches", "chushoku"]],
            [["dinners", "yushoku"]],
            [["snacks", "o-kashi"]],
            [["pumpkins", "kabocha"]],
            [["lobsters", "robusuta"]],
            [["cauliflowers", "kaurifurwa"]],
            [["cabbages", "kyabestu"]],
            [["celeries", "serori"]],
            [["chilli peppers", "togarashi"]],
            [["eggplants", "nasu"]],
            [["brocollis", "burokkori"]],
            [["spinaches", "horesno"]],
            [["bean sprouts", "moyashi"]],
            [["cheeses", "hizu"]],
            [["strawberries", "ichigo"]],
            [["figs", "ichijiku"]],
            [["plums", "puramu"]],
            [["lemons", "remon"]],
            [["blueberries", "buruberu"]],
            [["prunes", "purun"]],
            [["peaches", "momo"]],
            [["ice creams", "aisukurimu"]],
            [["chocolates", "chokoreto"]],
            [["juices", "jusu"]],
            [["soy sauces", "shoyu"]],
            [["sesames", "goma"]],
            [["oils", "abura"]],
            [["sausages", "chozume"]],
            [["cherries", "sakuranbo"]],
            [["hamburgers", "hanbaga"]]
    ];

     word_numbers = [
            [["one", "ichi"]],
            [["two", "ni"]],
            [["three", "san"]],
            [["four", "yon/shi"]],
            [["five", "go"]],
            [["six", "roku"]],
            [["seven", "nana/shichi"]],
            [["eight", "hachi"]],
            [["nine", "kyuu/ku"]],
            [["ten", "juu"]],
            [["eleven", "juuichi"]],
            [["twelve", "juuni"]],
            [["thirteen", "juusan"]],
            [["fourteen", "juuyon"]],
            [["fifteen", "juugo"]],
            [["sixteen", "juuroku"]],
            [["seventeen", "juunana"]],
            [["eighteen", "juuhachi"]],
            [["nineteen", "juukyuu"]],
            [["twenty", "nijuu"]],
            [["twenty-one", "nijuuichi"]],
            [["twenty-two", "nijuuni"]],
            [["twenty-three", "nijuusan"]],
            [["twenty-four", "nijuuyon"]],
            [["twenty-five", "nijuugo"]],
            [["twenty-six", "nijuuroku"]],
            [["twenty-seven", "nijuunana"]],
            [["twenty-eight", "nijuuhachi"]],
            [["twenty-nine", "nijuukyuu"]],
            [["thirty", "sanjuu"]]
    ];

     numbers = [
            [["1", "ichi"]],
            [["2", "ni"]],
            [["3", "san"]],
            [["4", "yon/shi"]],
            [["5", "go"]],
            [["6", "roku"]],
            [["7", "nana/shichi"]],
            [["8", "hachi"]],
            [["9", "kyuu/ku"]],
            [["10", "juu"]],
            [["11", "juuichi"]],
            [["12", "juuni"]],
            [["13", "juusan"]],
            [["14", "juuyon"]],
            [["15", "juugo"]],
            [["16", "juuroku"]],
            [["17", "juunana"]],
            [["18", "juuhachi"]],
            [["19", "juukyuu"]],
            [["20", "nijuu"]],
            [["21", "nijuuichi"]],
            [["22", "nijuuni"]],
            [["23", "nijuusan"]],
            [["24", "nijuuyon"]],
            [["25", "nijuugo"]],
            [["26", "nijuuroku"]],
            [["27", "nijuunana"]],
            [["28", "nijuuhachi"]],
            [["29", "nijuukyuu"]],
            [["30", "sanjuu"]]
    ];

     colours = [
            [["red", "akai"]],
            [["blue", "aoi"]],
            [["green", "midori"]],
            [["yellow", "kiiroi"]],
            [["black", "kuroi"]],
            [["white", "shiroi"]],
            [["gray", "guree"]],
            [["orange", "orenji"]],
            [["purple", "murasaki"]],
            [["pink", "pinku"]],
            [["brown", "chairo"]],
            [["gold", "kin iro"]],
            [["silver", "gin iro"]],
            [["beige", "beiju"]],
            [["turquoise", "taakoiizu"]],
            [["indigo", "indigo"]],
            [["violet", "baioretto"]],
            [["magenta", "majenta"]],
            [["cyan", "shian"]],
            [["lime", "raimu"]],
            [["teal", "tiiru"]],
            [["navy", "neibii"]],
            [["maroon", "maruun"]],
            [["olive", "oriibu"]],
            [["coral", "koraru"]],
            [["peach", "piichi"]],
            [["lavender", "rabendaa"]],
            [["fuchsia", "fukushia"]],
            [["khaki", "kaki"]],
            [["cream", "kuriimu"]]

    ];



     wordArrayList = [action, object, career, environment, position, time, stuff, description, clothing, feeling, food, personal, sentence_words, transportation, animal, body, pluralfood, numbers, word_numbers, colours
    ];




     Setence_arr = [
            [

                    [["The train is blue", "Densha wa aoidesu"]],
                    [["the car needs oil", "Kuruma ni wa oiru ga hitsuyōdesu"]],
                    [["he needs water", "Kare ni wa mizu ga hitsuyōdesu"]],
                    [["Apples are red", "Ringo wa akaidesu"]],
                    [["this room is bright because of the sunlight", "Kono heya wa taiyō no hikari no sei de akaruidesu"]],
                    [["this tall building is big", "Kono takai tatemono wa ōkīdesu"]],
                    [["the apple is big as the sun", "Ringo wa taiyō no yō ni ōkī"]],
                    [["some flowers are big others are not", "Ōkī hana mo areba,-sōdenai hana mo arimasu"]],

            ],

            [
                    [["He is going", "Kare wa ikimasu"]],
                    [["He is walking", "Kare wa aruite imasu"]],
                    [["He is running", "Kare wa hashitte imasu"]],
                    [["He is flying", "Kare wa tonde imasu"]],
                    [["He is moving", "Kare wa ugoite imasu"]],
                    [["He is jumping", "Kare wa tobihanete imasu"]],
                    [["He is coming", "Kare ga kimasu"]],
                    [["he is entering", "Kare wa haitte imasu"]],
                    [["he is looking", "Kare wa sagashiteimasu"]],
                    [["he is speaking", "Kare wa hanashite imasu"]],
                    [["he is searching", "Kare wa sagashiteimasu"]],
                    [["he is enjoying", "Kare wa tanoshinde imasu"]],
                    [["he is cooking", "Kare wa ryōri o shite imasu"]],
                    [["he is eating", "Kare wa tabete imasu"]],


            ],

            [

                    [["He is gone", "Kare wa inaku natte shimatta"]],
                    [["He is going to go", "Kare wa iku tsumoridesu"]],
                    [["He left", "Kare wa sarimashita"]],
                    [["He is leaving", "Kare wa shuppatsu shimasu"]],
                    [["He is going to leave", "Kare wa shuppatsu suru tsumoridesu"]],
                    [["He is leaving the house", "Kare wa ie o deru tsumoridesu"]],
            ],

            [
                    [["He is going to the school", "Kare wa gakkou ni iku tsumori desu"]],
                    [["He is walking to the school", "Kare wa gakkou made aruite imasu"]],
                    [["He is running university", "Kare wa daigaku e hashitte imasu"]],
                    [["He is flying to the park", "Kare wa kouen e tonde itte imasu"]],
                    [["He is moving to the library", "Kare wa toshokan e idou shite imasu"]],
                    [["He is jumping to the table", "Kare wa teeburu ni tobi notte imasu"]],
                    [["He is coming to the university", "Kare wa daigaku ni kite imasu"]],
                    [["he is entering the house", "Kare wa ie ni haitte imasu"]],
                    [["he is looking at the park", "Kare wa kouen o mite imasu"]],
                    [["he is speaking to me", "Kare wa watashi ni hanashikakete imasu"]],
                    [["he is searching the park", "Kare wa kouen o sagashite imasu"]],
                    [["he is enjoying the pen", "Kare wa pen o tanoshinde imasu"]],
                    [["he is cooking chicken", "Kare wa toriniku o ryouri shite imasu"]],
                    [["he is eating apple", "Kare wa ringo o tabete imasu"]],
            ],
            [
                    [["He made a tissue with plastic", "Kare wa purasuchikku de tisshu o tsukutta"]],
                    [["using a pen makes him happy", "Pen o tsukau koto wa kare o shiawase ni suru"]],
                    [["he made a pen out of plastic", "Kare wa purasuchikku de pen o tsukutta"]],
                    [["he is using the spoon", "Kare wa supuun o tsukatte imasu"]],
            ],
            [
                    [["he owns the pen", "Kare wa sono pen o shoyuu shite imasu"]],
                    [["he owns the car", "Kare wa sono kuruma o shoyuu shite imasu"]],
                    [["he owns the house", "Kare wa sono ie o shoyuu shite imasu"]],
                    [["the car belongs to him", "Sono kuruma wa kare no mono desu"]],
            ],
            [
                    [["he took a lot of pens", "Kare wa takusan no pen o totte kita"]],
                    [["the shop has lots of pens", "Sono mise ni wa takusan no pen ga arimasu"]],
                    [["He has enough pen", "Kare wa juubun na pen o motte imasu"]],
                    [["The box has enough pens", "Sono hako ni wa juubun na pen ga haitte imasu"]],
                    [["he has a variety of apples", "Kare wa samazama na ringo o motte imasu"]],
                    [["He is picking up the apples from the store", "Kare wa mise kara ringo o hirotte imasu"]],
                    [["He put the pen in the shop", "Kare wa mise ni pen o okimashita"]],
                    [["He got the pen from the shop", "Kare wa mise kara pen o moraimashita"]],
                    [["The restaurant will give you bread", "Sono resutoran wa anata ni pan o kureru deshou"]],
                    [["The restaurant gave him bread", "Sono resutoran wa kare ni pan o kuremashita"]],
                    [["He's carrying all the pens", "Kare wa subete no pen o hakonde imasu"]],
                    [["He received a pen from the store", "Kare wa mise kara pen o uketorimashita"]],
                    [["He replaced a pen", "Kare wa pen o koukan shimashita"]],
                    [["The house has a window", "Sono ie ni wa mado ga arimasu"]],
                    [["The house has a door", "Sono ie ni wa doa ga arimasu"]],
                    [["This house has more apples", "Kono ie ni wa motto takusan no ringo ga arimasu"]],
                    [["This house belongs to him", "Kono ie wa kare no mono desu"]],
                    [["This bag is his", "Kono kaban wa kare no mono desu"]],
                    [["This pen is part of that bag", "Kono pen wa sono kaban no ichibu desu"]],
                    [["This plastic is part of that kettle", "Kono purasuchikku wa sono kettoru no ichibu desu"]],
                    [["This room serves papers", "Kono heya wa pepaa o teikyou shimasu"]],
                    [["This restaurant serves food", "Kono resutoran wa tabemono o teikyou shimasu"]],
                    [["This plastic is for the kettle", "Kono purasuchikku wa kettoru no tame no mono desu"]],
            ],
            [
                    [["It's possible to play because it's warm", "Atatakai kara asobu koto ga kanou desu"]],
                    [["it's possible to play in the room because it's warm", "Heya ga atatakai kara heya de asobu koto ga kanou desu"]],
                    [["it's possible to go university but it's expensive", "Daigaku ni iku koto wa kanou desu ga, takai desu"]],
                    [["if you eat apples you will be strong", "Ringo o tabereba tsuyoku narimasu"]],
                    [["when I turned on the fan all the papers fell in the room", "Senpuuki o tsuketa toki, heya no pepaa ga zenbu ochimashita"]],
                    [["If I was you I would play more", "Watashi ga anata nara, motto asobimasu"]],
                    [["it might rain therefore I will take the jacket", "Ame ga furu kamoshirenai node, jaketto o motte ikimasu"]],
                    [["it might rain today", "Kyou wa ame ga furu kamoshirenai"]],
                    [["i think it might rain today", "Kyou wa ame ga furu kamoshirenai to omoimasu"]],
                    [["I think the pen is big", "Sono pen wa ookii to omoimasu"]],
                    [["I would travel if I had more money", "Motto okane ga areba ryokou suru deshou"]],
                    [["Apple is more popular than oranges", "Ringo wa orenji yori ninki ga arimasu"]],
                    [["Apple is better than oranges", "Ringo wa orenji yori yoi desu"]],
                    [["Eating is better than playing", "Taberu koto wa asobu koto yori yoi desu"]],
            ],
            [
                    [["The room came with so many pens", "Heya ni wa takusan no pen ga tsuite kita"]],
                    [["the pen is moving also the car is moving", "Pen mo ugouite iru shi, kuruma mo ugouite iru"]],
                    [["there is a cat inside the car", "Kuruma no naka ni neko ga iru"]],
                    [["there is a cat inside the car that is moving", "Ugouite iru kuruma no naka ni neko ga iru"]],
                    [["the cat is approaching the room", "Neko ga heya ni chikadzuite iru"]],
                    [["the pen is flying to the school", "Pen ga gakkou e tonde iru"]],
            ],
            [
                    [["There are lots of cars", "Takusan no kuruma ga aru"]],
                    [["There is a lot of pens in the room", "Heya ni wa takusan no pen ga aru"]],
                    [["The pen is over the car", "Pen ga kuruma no ue ni aru"]],
                    [["The ball is above the car", "Booru ga kuruma no ue ni aru"]],
                    [["He's at the station", "Kare wa eki ni iru"]],
                    [["The pen is inside the room", "Pen ga heya no naka ni aru"]],
                    [["The pen is above the table", "Pen ga teeburu no ue ni aru"]],
                    [["The pen is under the table", "Pen ga teeburu no shita ni aru"]],
                    [["The pen is next to the table", "Pen ga teeburu no tonari ni aru"]],
                    [["The pen is close to the table", "Pen ga teeburu no chikaku ni aru"]],
            ],
            [
                    [["When I eat I'm always in the park", "Watashi wa taberu toki, itsumo kouen ni imasu"]],
                    [["When you eat you can play", "Anata wa taberu toki, asobu koto ga dekimasu"]],
                    [["I usually eat in the morning", "Watashi wa taitei asa ni tabemasu"]],
                    [["I exercise twice a week", "Watashi wa isshuu kan ni nikai undou shimasu"]],
                    [["When it rains I go home", "Ame ga furu toki, watashi wa ie ni kaerimasu"]],
                    [["He plays out during the cold", "Kare wa samuisa no naka de soto de asobimasu"]],
                    [["Only when you eat you can play", "Anata ga taberu toki dake, asobu koto ga dekimasu"]],
                    [["After it rains I will eat", "Ame ga yanda ato, watashi wa tabemasu"]],
                    [["I will eat apple unless I go outside ", "Watashi wa soto ni ikanai kagiri, ringo o tabemasu"]],
                    [["once the apples are done you can play", "Ringo ga owattara, anata wa asobu koto ga dekimasu"]],
                    [["I eat apples every morning", "Watashi wa maiasa ringo o tabemasu"]],
            ],
            [
                    [["I wish to play", "Asobitai desu"]],
                    [["I wish I can play", "Asoberu to ii naa"]],
                    [["I like to study", "Benkyou suru no ga suki desu"]],
                    [["I want to play", "Asobitai desu"]],
                    [["I feel happy when I eat an apple", "Ringo o taberu toki, ureshii kimochi ni narimasu"]],
                    [["I'm excited when I eat an apple", "Ringo o taberu toki, wakuwaku shimasu"]],
                    [["I prefer going", "Iku hou ga suki desu"]],
                    [["I think learning English is important", "Eigo o manabu koto wa juuyou da to omoimasu"]],
                    [["I'm thinking of going", "Ikou to omotte imasu"]],
                    [["In my opinion, reading is fun.", "Watashi no iken de wa, yomu koto wa tanoshii desu"]],
                    [["I believe practice makes perfect.", "Renshuu wa kanpeki o tsukuru to shinjite imasu"]],
            ],
            [
                    [["There are three apples on the table", "Teeburu no ue ni mittsu no ringo ga arimasu"]],
                    [["The box has 5 apples", "Hako ni wa itsutsu no ringo ga haitte imasu"]],
                    [["The pen cost 5 bucks", "Sono pen wa go-doru shimashita"]],
                    [["", ""]],
            ],
            [
                    [["Who bag is this", "Kore wa dare no kaban desu ka"]],
                    [["How big is the pen?", "Sono pen wa dono kurai ookii desu ka?"]],
            ]
    ];
